// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnmtwZVJ6AyPtFRb5fwlAE4wTBl9774ik',
    appId: '1:289898165765:web:c138da732b36833c688e6c',
    messagingSenderId: '289898165765',
    projectId: 'teamsync-fd59a',
    authDomain: 'teamsync-fd59a.firebaseapp.com',
    databaseURL: 'https://teamsync-fd59a-default-rtdb.firebaseio.com',
    storageBucket: 'teamsync-fd59a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA85o4kQfRcdjcGvBaH-sz4EpqK9x-Xqc0',
    appId: '1:289898165765:android:fc2172afe982e318688e6c',
    messagingSenderId: '289898165765',
    projectId: 'teamsync-fd59a',
    databaseURL: 'https://teamsync-fd59a-default-rtdb.firebaseio.com',
    storageBucket: 'teamsync-fd59a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDITbqOq1kf1g6lvF9aUd5dh3FKnS2rchw',
    appId: '1:289898165765:ios:1a39b35b81d38f99688e6c',
    messagingSenderId: '289898165765',
    projectId: 'teamsync-fd59a',
    databaseURL: 'https://teamsync-fd59a-default-rtdb.firebaseio.com',
    storageBucket: 'teamsync-fd59a.appspot.com',
    iosBundleId: 'com.example.teamSyncPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDITbqOq1kf1g6lvF9aUd5dh3FKnS2rchw',
    appId: '1:289898165765:ios:4423674b4959b636688e6c',
    messagingSenderId: '289898165765',
    projectId: 'teamsync-fd59a',
    databaseURL: 'https://teamsync-fd59a-default-rtdb.firebaseio.com',
    storageBucket: 'teamsync-fd59a.appspot.com',
    iosBundleId: 'com.example.teamSyncPro.RunnerTests',
  );
}
